version: 0.0
os: linux
files:
   - source: goapp
     destination: /home/ec2-user/work
   - source: nginx
     destination: /home/ec2-user/work

hooks:
   ApplicationStop:
     - location: shells/stopgo.sh
       timeout: 180
   AfterInstall:
     - location: shells/copyNginxConf.sh
       timeout: 180
   ApplicationStart:
     - location: shells/rungo.sh
       timeout: 180
